site_name: IT Technical Documentation
site_url: http://www.indoguna.co.id/
site_description : Technical Documentation
site_author : Andy Utomo
copyright : Copyright &copy; 2014 Indoguna Utama PT, Maintained by the Andy Utomo
 
nav:
    - Tutorial :
        - Membuat Dokumentasi : int_createdocs.md 
        - Restart Program Pendukung SAP : restart_server.md 
    - Program Update : 
        - research & development : rnd_cnw.md
        - AR Invoice : arinv.md
theme : 
    name : material
    logo : asset/logocnw1.png
    favicon : asset/logocnw2.png
    palette:
        scheme: default
        primary: teal
extra_css:
    - css/extra.css
    - css/pdf-print.css
markdown_extensions:
    - toc:
        permalink: 
    - attr_list
    - def_list
    - tables
    - pymdownx.highlight:
        use_pygments: false
    - pymdownx.snippets
    - pymdownx.superfences  

plugins:
    - search    
    - mermaid2 
    - pdf-export:
        combined: false
        media_type: print
    - with-pdf:
        copyright: Copyright &copy; 2023 Andy Utomo.
        cover_subtitle: IT documentation with Markdown.
        output_path: ../document.pdf