site_name: IT Technical Documentation

nav:
    - Tutorial :
        - Membuat Dokumentasi : int_createdocs.md 
        - Restart Program Pendukung SAP : restart_server.md 
    - Program Update : 
        - research & development : rnd_cnw.md
        - AR Invoice : arinv.md
theme : 
    name : material
    logo : asset/logocnw1.png
    favicon : asset/logocnw2.png
    palette:
        scheme: default
        primary: teal
plugins:
    - search    
    - mermaid2
    - pdf-export:
        combined: false
        media_type: print