site_name: IT Documentation

nav:
    - Introduction: 'index.md'
    - Tutorial :
        - Membuat Dokumentasi : int_createdocs.md 
    - Program Update : 
        - Integration Efaktur : efaktur.md
        - Integration SAP : cnwls.md
theme : united   
plugins:
    - search 
    - mermaid2
