site_name: IT Technical Documentation

nav:
    - Introduction: index.md
    - Tutorial :
        - Technical Environment : it_technical.md
        - Membuat Dokumentasi : int_createdocs.md 
        - Restart Program Pendukung SAP : restart_server.md 
        - Proses PI  : pi_manual.md 
    - Program Update : 
        - Integration Efaktur : efaktur.md
        - Integration SAP : cnwls.md
        - research & development : rnd_cnw.md
theme : material
plugins:
    - search    
    - mermaid2
    - pdf-export:
        combined: false
        media_type: print